- name: Get IP address for Hub
  shell: "jaia ip h{{ hub_id }}f{{ jaiabot_embedded_fleet_id }}"
  register: hub_ip_result
  
- name: Set hub IP
  set_fact:
    hub_ip: '{{ hub_ip_result.stdout}}'
    
- name: Check if version.txt exists
  uri:
    url: "http://{{ hub_ip }}/updates/major_upgrade/version.txt"
    method: HEAD
    return_content: no
    status_code: 200
  register: url_check
  failed_when: url_check.status != 200
  ignore_errors: no

- name: Download version.txt
  get_url:
    force: true
    url: "http://{{ hub_ip }}/updates/major_upgrade/version.txt"
    dest: "{{ upgrade_dir }}/version.txt"
  
- name: Read the version file content into a fact
  slurp:
    src: "{{ upgrade_dir }}/version.txt"
  register: version_file

- name: Set fact for version content
  set_fact:
    rootfs_major_version: "{{ version_file.content | b64decode | trim }}"

- name: Extract version string
  set_fact:
    jaiabot_major_version: "{{ rootfs_major_version | regex_search('v(\\d+\\.\\d+\\.\\d+.*)$', '\\1') | first }}"
