---
- name: Create new VirtualFleet EC2 instances (and delete any old ones)
  hosts: localhost
  gather_facts: yes
  vars:
    warp: 5
    instance_type: t3a.small
    volume_size_gb: 16
    server_ssh_privkey_path: /home/jaia/.ssh/id_ed25519
    server_ssh_pubkey_path: /home/jaia/.ssh/id_ed25519.pub
    virtualhub_ssh_privkey_path: /home/jaia/.ssh/virtualhub
    virtualhub_ssh_pubkey_path: /home/jaia/.ssh/virtualhub.pub
    fleet_cfg_path: /etc/jaiabot/virtualfleet.cfg
    user_data_path: /etc/jaiabot/virtualfleet-user-data
    bootdir_base: /tmp/virtualfleet-boot
    
  tasks:
    - include_tasks: tasks/gen-node-map.yml

    - name: Read cloud.env
      include_tasks: tasks/read-env.yml
      tags: read

    - name: VirtualFleet VPN setup
      include_tasks: tasks/vfleet-vpn-setup.yml
      tags: read

    - name: Read IP addresses
      include_tasks: tasks/read-ip-addresses.yml    
      tags: read

    - name: Read publickeys configured on Cloudhub and use these for VirtualFleet
      set_fact:
        user_ssh_pubkeys: "{{ lookup('file', '/home/jaia/.ssh/authorized_keys') }}"
      tags: read

    - name: Generate OpenSSH keypair for Cloudhub
      community.crypto.openssh_keypair:
        path: "{{ server_ssh_privkey_path }}"
        type: ed25519
      tags: read

    - name: Generate OpenSSH keypair for VirtualHub
      community.crypto.openssh_keypair:
        path: "{{ virtualhub_ssh_privkey_path }}"
        type: ed25519
      tags: read

    - name: Generate fleet config file
      template:
        src: templates/fleet.cfg.j2
        dest: "{{ fleet_cfg_path }}"

    - name: Create VirtualFleet inventory 
      shell: |
        /usr/bin/jaia-create-ansible-inventory.sh -b "{{ range(1, n_bots|int + 1) | join(',') }}" -h "1" -f {{ cloud_env_vars.jaia_fleet_index }} -n vfleet_vpn  > /etc/jaiabot/vfleet-inventory.yml
      become: yes
        
    - name: Create the user data directories
      file:
        path: "{{ bootdir_base }}/{{ item.node_type }}{{ item.node_id }}"
        state: directory
      loop: "{{ node_map }}"

    - name: Generate VirtualFleet user data
      template:
        src: templates/cloud-vfleet-user-data.yml.j2
        dest: "{{ bootdir_base }}/{{ item.node_type }}{{ item.node_id }}/cloud-vfleet-user-data.yml"
      loop: "{{ node_map }}"
        
    - name: Create user data
      shell: |
        bootdir={{ bootdir_base }}/{{ item.node_type }}{{ item.node_id }}
        mkdir -p ${bootdir}/jaiabot/init
        cp /usr/share/jaiabot/init/first-boot.preseed.yml.j2 ${bootdir}/jaiabot/init/
        jaia admin fleet generate {{ fleet_cfg_path }} --mode simulation {{ item.node_type }} {{ item.node_id }} --bootdir ${bootdir}
        cloud-init devel make-mime -a ${bootdir}/cloud-vfleet-user-data.yml:cloud-config -a /usr/share/jaiabot/init/common-first-boot.yml:cloud-config -a ${bootdir}/jaiabot/init/first-boot.preseed.yml:cloud-config > ${bootdir}/user-data
      loop: "{{ node_map }}"
        
    - name: Find latest AMI
      amazon.aws.ec2_ami_info:
        region: "{{ cloud_env_vars.jaia_aws_region }}"
        filters:
          "tag:jaiabot-rootfs-gen_repository": "{{ cloud_env_vars.jaia_aws_virtualfleet_repository }}"
          "tag:jaiabot-rootfs-gen_repository_version": "{{ cloud_env_vars.jaia_aws_virtualfleet_repository_version }}"
      register: ami_info

    - name: Set ami_info (present)
      set_fact:
        ami_id: "{{ ami_info.images[0].image_id }}"

    - name: Terminate any old EC2 instances from this fleet to ensure consistency and correct VPN settings
      amazon.aws.ec2_instance:
        region: "{{ cloud_env_vars.jaia_aws_region }}"
        filters:        
          tag:jaia_instance_type: "virtualfleet"
          tag:jaia_fleet: "{{ cloud_env_vars.jaia_fleet_index }}"
          tag:jaia_customer: "{{ jaia_customer_no_quotes }}"
        wait: true
        state: terminated

    - name: Clear out old known_hosts file
      file:
        path: /home/jaia/.ssh/known_hosts
        state: absent
        
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "jaia__Virtual{{ item.node_type | capitalize }}{{ item.node_id }}__{{ jaia_customer_no_quotes }}"
        region: "{{ cloud_env_vars.jaia_aws_region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ cloud_env_vars.jaia_aws_virtualfleet_security_group }}"
        subnet_id: "{{ cloud_env_vars.jaia_aws_virtualfleet_wlan_subnet_id }}"
        network:
          private_ip_address: "{{ wlan_ipv4_addresses[item.node_type][item.node_id] }}"
          description: "wlan"
        volumes:
        - device_name: /dev/sda1
          ebs:
            delete_on_termination: true
            volume_type: gp3
            volume_size: "{{ volume_size_gb }}"
        tags:
          jaia_instance_type: "virtualfleet"
          jaia_node_type: "{{ item.node_type }}"
          jaia_node_id: "{{ item.node_id }}"
          jaia_fleet: "{{ cloud_env_vars.jaia_fleet_index }}"
          jaia_customer: "{{ jaia_customer_no_quotes }}"
          jaiabot-rootfs-gen_repository: "{{ cloud_env_vars.jaia_aws_virtualfleet_repository }}"
          jaiabot-rootfs-gen_repository_version: "{{ cloud_env_vars.jaia_aws_virtualfleet_repository_version }}"          
        user_data: "{{ lookup('file', '{{ bootdir_base }}/{{ item.node_type }}{{ item.node_id }}/user-data') }}"
        wait: false
        state: present
      loop: "{{ node_map }}"
      # Avoid writing private Wireguard keys into the log
      no_log: true
      register: ec2_instances
        
    - name: Update peer blocks in WireGuard config
      blockinfile:
        path: /etc/wireguard/wg_virtualfleet.conf
        block: |
          {{ lookup('template', 'templates/wireguard_peer.j2') }}
        marker: "# {mark} PEER {{ item.item.node_type }} {{ item.item.node_id }}: AUTOGENERATED"
        create: no
      loop: "{{ ec2_instances.results }}"
      become: yes

    - name: Restart WireGuard
      become: yes
      shell: "systemctl restart wg-quick@wg_virtualfleet"

    - name: Write /etc/hosts
      include_tasks: tasks/write-etc-hosts.yml
      
    - name: Wait for hosts
      include_tasks: tasks/wait-hosts.yml

# TODO
# SPEED up first boot
