#cloud-config

# Allows this config to merge correctly with first-boot.preseed.yml
# See https://cloudinit.readthedocs.io/en/latest/reference/merging.html
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
   
# Set temporary hostname, will be updated by jaiabot-embedded postinst
hostname: jaia-unnamed
manage_etc_hosts: localhost

# jaia user
users:
  - name: jaia
    groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true

# Disallow password login on SSH
ssh_pwauth: false

# Resize data partition to fill disk
growpart:
  mode: auto
  devices: [/var/log]

bootcmd:
  # Disable networkd wait as we're using /etc/network/interfaces on Rasp Pi
  - if [ "$(cloud-init query cloud_id)" = "nocloud" ]; then systemctl mask systemd-networkd-wait-online.service; fi
  
runcmd:
  # Set up log disk
  - btrfs filesystem resize max /var/log
  - mkdir -p /var/log/jaiabot
  # allow jaia user to write logs
  - chown -R jaia:jaia /var/log/jaiabot
  - mkdir -p /var/log/apache2
  # Set up I2C
  - /boot/firmware/jaiabot/init/setup-i2c.sh
  # Install jaiabot embedded for unprivileged jaia user
  - env USER=jaia apt -y install /opt/jaiabot-embedded*.deb
  # Append first boot date to version file
  - echo "JAIABOT_FIRST_BOOT_DATE=\"`date -u`\"" >> /etc/jaiabot/version
  # Set overlay to take effect on next boot
  - echo "overlayroot=device:dev=/dev/disk/by-label/overlay,timeout=60,recurse=0" >> /etc/overlayroot.conf
  
# Reboot for overlay to take effect
power_state:
  mode: reboot
  timeout: 30
  condition: true
